DI-2713: Reverting python2
jampp/pydruid pull request #6
Opened 2022-06-27 17:52 UTC by Rcharriol

Remove py2 support and 
upgrade black version.
Fixing CI Tests

2022-06-27 19:12 UTC, mauguignard requested changes
The test files must be updated as well.

2022-06-27 19:12 UTC, mauguignard commented on CHANGELOG.md
> +### 0.8.0j (Unreleased)
You need to bump the version in `setup.py`

2022-06-27 19:12 UTC, mauguignard commented on requirements-dev.in
> -typing; python_version < "3.0"
You need to run `pip-compile --no-annotate requirements-dev.in` so these changes are applied.

2022-06-27 19:12 UTC, mauguignard commented on requirements-dev.in
> -typing; python_version < "3.0"
You are missing the changes in `requirements.in` as well.

2022-06-27 19:12 UTC, mauguignard commented on tox.ini
> +[testenv:{py37}-pytest]
You should be able to simplify this file a lot now:

```
[testenv:pytest]
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest {posargs}
deps =
    -rrequirements.txt
    -rrequirements-dev.txt
parallel_show_output = true
usedevelop = true

[testenv:black]
commands =
    black --target-version=py37 --check pydruid setup.py tests
deps =
    black==22.3.0

[testenv:isort]
commands =
    isort --check-only --recursive pydruid setup.py tests
deps =
     isort==4.3.21

[testenv:flake8]
commands =
    flake8 pydruid setup.py tests
deps =
    flake8==3.9.1

[tox]
envlist =
    black
    flake8
    isort
    pytest
skipdist = true

[gh-actions]
python =
    3.7: py37
```

2022-06-28 17:29 UTC, gonzalezzfelipe approved these changes

2022-06-28 17:49 UTC, mauguignard commented on tox.ini
> +    3.7: py37
Hmm, the tests do not seem to have been executed.

Maybe it needs to be:

```suggestion
    3.7: black,flake8,isort,pytest
```

2022-06-28 17:55 UTC, Rcharriol commented on tox.ini
> +    3.7: py37
Well, i really doubted that line, it seemed very odd, but since i dont know anything about this, never done it before, it blindly trusted Mauri

2022-06-28 17:56 UTC, mauguignard commented on tox.ini
> +    3.7: py37
:see_no_evil:

2022-06-28 17:57 UTC, mauguignard approved these changes
:ok_hand:

2022-06-28 18:02 UTC, merged